# Generated by Django 5.1.4 on 2025-07-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.ImageField(upload_to='blogi_mages/'),
        ),
    ]
